language: haskell
ghc:
  - 7.8
  - 7.10
install:
  - cabal install alex
  - cabal install wheb-base/Wheb.cabal --enable-tests
  - cabal install plugins/wheb-mongo/wheb-mongo.cabal --enable-tests
  - cabal install plugins/wheb-strapped/wheb-strapped.cabal --enable-tests
  - cabal install plugins/wheb-redis/wheb-redis.cabal --enable-tests
  - cabal install blaze-html
  - cabal install web-routes-boomerang
script:
  - cd wheb-base && cabal configure -v0 --enable-tests && cabal build -v0 && cabal test
  - cd ..
  - ghc -c examples/Blaze.hs
  - ghc -c examples/File.hs
  - ghc -c examples/Main.hs
  - ghc -c examples/Minimal.hs
  - ghc -c examples/Mongo.hs
  - ghc -c examples/Routes.hs
  - ghc -c examples/Stateful.hs
  - ghc -c examples/WebRoutes.hs
  - ghc -c examples/WebSockets.hs
  - ghc -c examples/Redis.hs